version: '3.5'
services:
  codeception:
    image: ambimax/php7.0-cli-stretch:7.0.31
    entrypoint: codecept
    working_dir: /var/www
    volumes:
      - "${PWD}:/var/www"
    networks:
      - frontend

  zalenium:
    image: "dosel/zalenium"
    privileged: true
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    expose:
      - 5555
    ports:
      - 4444:4444
    command: >
      start --screenWidth 1930 --screenHeight 1090
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    networks:
      frontend:
      aliases:
      - zalenium.docker

  # requirement for zalenium
  selenium:
    image: elgalu/selenium

networks:
  frontend: